template.sh references an invalid template: terraform-verify-oss, available options: ./templates/frontend-library-oss.config.yml
./templates/go-distribution-oss.config.yml
./templates/go-library-oss.config.yml
./templates/java-library-oss.config.yml
